// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx1f4YGLN-mdYWlH2eDeZmuK0MkLIH8i8',
    appId: '1:462614310604:web:df514817c681dff1f15c69',
    messagingSenderId: '462614310604',
    projectId: 'quiz-app-work',
    authDomain: 'quiz-app-work.firebaseapp.com',
    storageBucket: 'quiz-app-work.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPQfP6SD5DSXWmtFOQXKP71zZeaQFYhmE',
    appId: '1:462614310604:android:275a8821043c3aeaf15c69',
    messagingSenderId: '462614310604',
    projectId: 'quiz-app-work',
    storageBucket: 'quiz-app-work.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNCItR7oxJ9xrCzGALgQNKFu5JJM4qK4g',
    appId: '1:462614310604:ios:48e631e0639de955f15c69',
    messagingSenderId: '462614310604',
    projectId: 'quiz-app-work',
    storageBucket: 'quiz-app-work.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNCItR7oxJ9xrCzGALgQNKFu5JJM4qK4g',
    appId: '1:462614310604:ios:48e631e0639de955f15c69',
    messagingSenderId: '462614310604',
    projectId: 'quiz-app-work',
    storageBucket: 'quiz-app-work.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx1f4YGLN-mdYWlH2eDeZmuK0MkLIH8i8',
    appId: '1:462614310604:web:2065fe22801f9158f15c69',
    messagingSenderId: '462614310604',
    projectId: 'quiz-app-work',
    authDomain: 'quiz-app-work.firebaseapp.com',
    storageBucket: 'quiz-app-work.firebasestorage.app',
  );

}